# -*- mode: python -*-

# Import('env')
# env = env.Clone()
# env.MergeFlags('-I/home/zhouqiang/tank_searcher')
# print env

libcommon_sources = [
    'SimpleStorage.cpp',
    ]

SharedLibrary(target = 'Tank_Searcher_Index',
             source = libcommon_sources)

SConscript(['test/SConscript'])
