# -*- mode: python -*-
Import('env')
env.MergeFlags('-I.')

libcommon_sources = [
    'SimpleStorage.cpp',
    ]

env.SharedLibrary(target = 'Tank_Searcher_Index',
              source = libcommon_sources)

SConscript('test/SConscript', 'env')
