# -*- mode: python -*-

Import('env')
env.MergeFlags('-I.')

libcommon_sources = [
    'BuildConfig.cpp',
    'BuildConfigParser.cpp',
    'ModulesConfig.cpp',
    'DocumentProcessorConfig.cpp',
    'BuildConfigValidate.cpp',
    ]

env.SharedLibrary(target = 'Tank_Searcher_Config',
              source = libcommon_sources)

SConscript('test/SConscript', 'env')
