# -*- mode: python -*-
import os
Import('env')

libcommon_sources = [
    'mainTest.cpp',
    'FileUtilTest.cpp',
    'JsonUtilTest.cpp'
    ]

def aRunUnitTest(env, src):
    env.Program('tank_searcher_util_test',
        libcommon_sources, 
        LIBS = ['glog', 'gtest', 'folly','double-conversion','Tank_Searcher_Util', 'pthread'], 
        LIBPATH = ['.', '../', '../../../lib/'])

    cmd ="/usr/bin/env install_root=%s GLOG_logtostderr=1 LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib:/usr/lib64:/usr/lib:%s/build/util/ ./tank_searcher_util_test" % (env['install_root'], env['install_root'])
    print cmd
    os.system(cmd)

env.AddMethod(aRunUnitTest, 'ut')
env.ut(libcommon_sources)

