# -*- mode: python -*-

# Import('env')
# env = env.Clone()
# env.MergeFlags('-I/home/zhouqiang/tank_searcher')
# print env

libcommon_sources = [
    'BuildConfig.cpp',
    'BuildConfigParser.cpp',
    ]

SharedLibrary(target = 'Tank_Searcher_Config',
             source = libcommon_sources,
              CCFLAGS = '-I. -std=c++11')

SConscript(['test/SConscript'])
