# -*- mode: python -*-

# Import('env')
# env = env.Clone()
# env.MergeFlags('-I/home/zhouqiang/tank_searcher')
# print env

libcommon_sources = [
    'FileUtil.cpp',
    ]

SharedLibrary(target = 'Tank_Searcher_Util',
             source = libcommon_sources,
              CCFLAGS = '-I.')

SConscript(['test/SConscript'])
