# -*- mode: python -*-

Import('env')
env.MergeFlags('-I.')

libcommon_sources = [
    'FileUtil.cpp',
    'JsonUtil.cpp',
    ]

env.SharedLibrary(target = 'Tank_Searcher_Util',
             source = libcommon_sources)

SConscript('test/SConscript', 'env')
