# -*- mode: python -*-
import os


libcommon_sources = [
    'mainTest.cpp',
    ]

Program('tank_searcher_config_test',
        libcommon_sources, 
        LIBS = ['glog', 'gtest', 'folly','double-conversion','Tank_Searcher_Config', 'pthread'], 
        LIBPATH = ['.', '../', '../../../lib/'],
        CCFLAGS = '-Iinclude/ -I. -std=c++11')

cmd ="/usr/bin/env GLOG_logtostderr=1 LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib:/usr/lib64:/usr/lib:/home/zhouqiang/svn/tank_searcher/tank_searcher/util/:/usr/lib/x86_64-linux-gnu/ ./tank_searcher_config_test"
print cmd
os.system(cmd)
