# -*- mode: python -*-

Import('env')
env.MergeFlags('-I.')

libcommon_sources = [
    'BuilderProcessor.cpp',
    'BuilderProcessorManager.cpp',
    ]

env.SharedLibrary(target = 'Tank_Searcher_Builder',
             source = libcommon_sources)

SConscript('test/SConscript', 'env')
