# -*- mode: python -*-
import os
Import('env')

libcommon_sources = [
    'mainTest.cpp',
    'SimpleStorageTest.cpp',
    ]


def aRunUnitTest(env, src):
    env.Program('tank_searcher_index_test',
        src, 
        LIBS = ['glog', 'gtest', 'Tank_Searcher_Index', 'pthread'], 
        LIBPATH = ['.', '../', '../../../lib/'])

    cmd ="/usr/bin/env GLOG_logtostderr=1 LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib:/usr/lib64:/usr/lib:%s/build/index/ ./tank_searcher_index_test" % env['install_root']
    print cmd
    os.system(cmd)

env.AddMethod(aRunUnitTest, 'ut')
env.ut(libcommon_sources)
