# -*- mode: python -*-
import os, sys
Import('env')
SConscript('index/SConscript', 'env')
SConscript('builder/SConscript', 'env')
SConscript('util/SConscript', 'env')
SConscript('config/SConscript', 'env')




